
[env]
TERM = "xterm-256color"

[font]
size = 13.0

# if true, alacritty uses its own font for box drawing. cool default unless you use a nerd font
builtin_box_drawing = false

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[bell]
# test with `tput bel`
duration = 0
# duration = 500
color = "#600000"

[mouse]
hide_when_typing = true 

# what are those?
[[keyboard.bindings]]
chars = '\p'
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = '\n'
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

# option movement
[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Option"

# command movement
[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations_theme_variant = "Dark"
dynamic_title = true
startup_mode = "Windowed"
decorations = "Full"
resize_increments = true

# this is cool if you Fullscreen also has a wallpaper ... looking at you MacOS
# opacity = 0.9
# blur = true

# this is cool if youre on an english keyboard...
# option_as_alt = "Both"

[window.dimensions]
columns = 135
lines = 50

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
